server:
  port: 8585

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://kandula.db.elephantsql.com/fnbxxzdf
    username: fnbxxzdf
    password: 5lWJNZIfzUte4H0FUK0g3OtXN8MfazeE
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      mode: always